import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Hind_Siliguri,
} from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import Marquee from "@/component/Marquee";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["latin", "bengali"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="bn"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} ${hindSiliguri.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />

        <Suspense fallback={<div />}>
          <Marquee />
        </Suspense>

        {children}
      </body>
    </html>
  );
}